[package]
name = "counter_program"
version = "0.1.0"
edition = "2021"

[dependencies]
borsh = "1.5.1"
solana-program = "1.18.26"

[lib]
crate-type = ["cdylib", "lib"]
name = "counter"

[dev-dependencies]
solana-program-test = "1.18.26"
solana-sdk = "1.18.26"
tokio = "1.41.0"
